# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sala', models.CharField(max_length=50)),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField(default=0)),
                ('data_entrada_pctec', models.DateTimeField(verbose_name='Data de Entrada no PCTec')),
                ('data_abertura', models.DateTimeField(verbose_name='Data de Abertura')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pctec.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.IntegerField(default=0)),
                ('rg', models.IntegerField(default=0)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pctec.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pctec.Telefone'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='funcionarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pctec.Funcionario'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pctec.Telefone'),
        ),
    ]
