# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0002_auto_20160720_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='data_abertura',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='data_entrada_pctec',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Entrada no PCTec'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tel1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tel2',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tel3',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel2',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel3',
            field=models.CharField(max_length=14),
        ),
    ]
