# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0006_empresa_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='Colaboradores',
        ),
        migrations.AddField(
            model_name='empresa',
            name='Colaboradores',
            field=models.ManyToManyField(to='pctec.Colaborador'),
        ),
    ]
