# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0008_auto_20160721_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='data_entrada_pctec',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razao_social',
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
