# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0011_auto_20160726_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pais',
            field=models.CharField(default='', max_length=50),
        ),
    ]
