# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0013_auto_20160812_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='colaboradores/'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
