# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0016_colaborador_cracha'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='sobrenome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
