# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 10:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0017_colaborador_sobrenome'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_entrada',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Entrada'),
        ),
    ]
