# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pctec', '0018_colaborador_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='instituicao',
            field=models.CharField(default='PCTec', max_length=50, verbose_name='Telefone'),
        ),
    ]
