# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=9)),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador_multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(blank=True, max_length=10)),
                ('expeditor', models.CharField(blank=True, max_length=10)),
                ('tel1', models.CharField(max_length=14, verbose_name='Telefone 1')),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('status_cracha', models.CharField(max_length=8)),
                ('automovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multincubadora.Automovel')),
            ],
        ),
        migrations.CreateModel(
            name='Consultores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('empresa', models.TextField()),
                ('redes_sociais', models.TextField(blank=True, null=True)),
                ('eixo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_Junior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('email_responsavel', models.TextField(blank=True, null=True)),
                ('tel1', models.CharField(max_length=14, verbose_name='Telefone 1')),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='prjr/')),
            ],
        ),
        migrations.CreateModel(
            name='Graduada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(default='', max_length=14)),
                ('data_saida', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('socio', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('enviar_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incubada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(default='', max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('sala', models.CharField(max_length=50)),
                ('tel1', models.CharField(max_length=14, verbose_name='Telefone 1')),
                ('site', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('blog', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('descricao', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='incubada/')),
            ],
        ),
    ]
