# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubada',
            name='socio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='graduada',
            name='enviar_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='blog',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='tel1',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
