# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0002_auto_20160810_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubada',
            name='responsavel_financeiro',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
