# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0003_incubada_responsavel_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador_multi',
            name='tel1',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empresa_junior',
            name='tel1',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='incubada',
            name='tel1',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
    ]
