# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0005_colaborador_multi_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='cor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='placa',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='colaborador_multi',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='colaborador_multi',
            name='tel1',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
    ]
