# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0006_auto_20160810_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubada',
            name='logo',
            field=models.ImageField(blank=True, default='multincubadora/unb.png', null=True, upload_to='incubada/'),
        ),
    ]
