# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0007_auto_20160810_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador_multi',
            name='foto',
            field=models.ImageField(blank=True, default='/pctec/static/pctec/no_foto.png', null=True, upload_to='colaboradores_multi/'),
        ),
    ]
