# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0008_colaborador_multi_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador_multi',
            name='foto',
            field=models.ImageField(blank=True, default='/colaboradores_multi/no_foto.png', null=True, upload_to='colaboradores_multi/'),
        ),
    ]
