# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0010_auto_20160825_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador_Empresa_Junior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(blank=True, max_length=10)),
                ('expeditor', models.CharField(blank=True, max_length=10)),
                ('tel1', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, default='/colaboradores_multi/no_foto.png', null=True, upload_to='colaboradores_multi/')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multincubadora.Empresa_Junior')),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
