# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0012_colaborador_empresa_junior_presidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultores',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='consultores',
            name='tel1',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
    ]
