# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0013_auto_20160826_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultores',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
