# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multincubadora', '0014_auto_20160826_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador_empresa_junior',
            name='instituicao',
            field=models.CharField(default='Multincubadora', max_length=50, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='colaborador_multi',
            name='instituicao',
            field=models.CharField(default='Multincubadora', max_length=50, verbose_name='Telefone'),
        ),
    ]
